apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: trio-dev
spec:
  project: default
  source:
    path: ./k8s-resources/trio/dev
    repoURL: https://github.com/nightmar39/cd-five-mins.git
    targetRevision: hosted-demo
    helm:
      valueFiles:
        - values.yaml
      parameters:
        - name: buildID
          value: argocd
  destination:
    name: in-cluster
    namespace: cf-demo
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
    syncOptions:
      - PrunePropagationPolicy=foreground
      - Replace=false
      - PruneLast=false
      - Validate=true
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=false
